services:
    coursero_db:
        image: mariadb:latest
        container_name: coursero_db
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - "8000:3306"
        healthcheck:
            test: ["CMD-SHELL", "mariadb-admin ping -u root -p$MYSQL_ROOT_PASSWORD || exit 1"]
            interval: 5s
            timeout: 5s
            retries: 20

    coursero_web:
        build: ./
        container_name: coursero_web
        depends_on:
            coursero_db:
                condition: service_healthy
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html
